# Generated by Django 4.2.7 on 2023-12-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
    ]
