# Generated by Django 4.2.7 on 2023-12-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20231208_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('document_proofs', models.TextField()),
                ('agreement_end_date', models.DateField()),
                ('monthly_rent_date', models.PositiveIntegerField()),
            ],
        ),
    ]
