# Generated by Django 4.2.7 on 2023-12-08 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='unit_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.unit'),
            preserve_default=False,
        ),
    ]
