# Generated by Django 4.2.7 on 2023-12-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_tenant_unit_tenant'),
    ]

    operations = [
    ]
