# Generated by Django 4.2.7 on 2023-12-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20231208_2037'),
    ]

    operations = [
    ]
